### ISSUE TITLE
Allow multiple SLURM partitions in a single pcluster

### ISSUE THREAD

**Issue by jplanasc** [openbraininstitute/hpc-resource-provisioner#56]
I think it would be beneficial to have different SLURM partitions (`queues` in AWS terminology) to manage where we launch jobs.

Most likely the `choose_tier` function in [pcluster_manager.py](https://github.com/openbraininstitute/hpc-resource-provisioner/blob/main/hpc_provisioner/src/hpc_provisioner/pcluster_manager.py) would need to be re-thought to get something similar to the following config:
```
Region: us-east-1
Image:
  ...
Monitoring:
  ...
HeadNode: ...
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    EnableMemoryBasedScheduling: true
    Dns:
      DisableManagedDns: true
      UseEc2Hostnames: true
  SlurmQueues:
    - Name: partition1
      ...
    - Name: partition2
      ...
```

With this, we would see 2 partitions in the cluster, similar to:
```
 $ sinfo
 PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
 partition1   up   infinite      3  idle~ efa-dy-partition1-[1-4]
 partition2   up   infinite      1  idle  efa-dy-partition2-1
```

Relevant references:
https://docs.aws.amazon.com/parallelcluster/latest/ug/tutorial-create-cluster-terraform-define.html
https://docs.aws.amazon.com/parallelcluster/latest/ug/multiple-queue-mode-slurm-user-guide-v3.html
